plugins { id 'com.android.application' }

android {
    namespace 'com.microllate.gboardword'
    compileSdk 35

    defaultConfig {
        applicationId 'com.microllate.gboardword'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
